version: "3.9"

services:

  frontend:
    build: ./frontend
    container_name: react_app
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    volumes:
      - frontend_access_logs:/var/log/nginx/access
      - frontend_error_logs:/var/log/nginx/error
    networks:
      - mern_network

  backend:
    build: ./backend
    container_name: node_api
    restart: always
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_DB: ${MONGO_DB}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      NODE_PORT: 5003
    ports:
      - "5003:5003"
    depends_on:
      - mongodb
    volumes:
      - backend_logs:/app/logs
    networks:
      - mern_network

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    command: ["mongod","--logpath","/var/log/mongodb/mongod.log"]
    volumes:
      - mongo_data:/data/db
      - mongo_logs:/var/log/mongodb
    networks:
      - mern_network


volumes:
  mongo_data:
  mongo_logs:
  backend_logs:
  frontend_access_logs:
  frontend_error_logs:

networks:
  mern_network:
    driver: bridge
